apiVersion: v1
kind: Service
metadata:
  name: docker-kub-demo
  namespace: dev
spec:
  type: NodePort
  selector:
    app: docker-kub-demo
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
